### ISSUE TITLE
LIMIT ? OFFSET ?  쿼리문 바인딩 오류

### ISSUE THREAD

**Issue by hyemin12** [hyemin12/book-store-project#11]
## LIMIT ? OFFSET ?  쿼리문 오류
values (바인딩 매개변수)도 숫자 타입으로 잘 들어가는데, `Incorrect arguments to mysqld_stmt_execute` 오류가 발생...

### 오류 예1
POST, localhost:8888/books?page=1
sql values = [ 8, 0 ]
```js
Error: Incorrect arguments to mysqld_stmt_execute
    at PromisePoolConnection.execute (C:\Users\user\Desktop\JS-project\book-store-api\node_modules\mysql2\promise.js:112:22)
    at getSqlQueryResult (C:\Users\user\Desktop\JS-project\book-store-api\utils\getSqlQueryResult.js:6:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getBooks (C:\Users\user\Desktop\JS-project\book-store-api\controller\booksController.js:31:28) {
  code: 'ER_WRONG_ARGUMENTS',
  errno: 1210,
  sql: 'SELECT * FROM books LIMIT ? OFFSET ?',
  sqlState: 'HY000',
  sqlMessage: 'Incorrect arguments to mysqld_stmt_execute'
}
```
### 오류 예2
POST, localhost:8888/books/search?query=모던&page=1
sql values = [ '모던', 6, 0 ] 
```js
Error: Incorrect arguments to mysqld_stmt_execute
    at PromisePoolConnection.execute (C:\Users\user\Desktop\JS-project\book-store-api\node_modules\mysql2\promise.js:112:22)
    at getSqlQueryResult (C:\Users\user\Desktop\JS-project\book-store-api\utils\getSqlQueryResult.js:6:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getSearchBooks (C:\Users\user\Desktop\JS-project\book-store-api\controller\booksController.js:60:28) {
  code: 'ER_WRONG_ARGUMENTS',
  errno: 1210,
  sql: '\n' +
    '    SELECT * FROM books \n' +
    '    WHERE title LIKE CONCAT("%", ?, "%") \n' +
    '    LIMIT ? OFFSET ?',
  sqlState: 'HY000',
  sqlMessage: 'Incorrect arguments to mysqld_stmt_execute'
}
```

### 오류 예3
하드코딩으로 직접 값을 입력해도 동일한 오류가 발생
```js
  const sql = `
    SELECT * FROM books 
    WHERE title LIKE CONCAT("%", ?, "%") 
    LIMIT ? OFFSET ?`;

const { rows, conn } = await getSqlQueryResult(sql, ['모던',8,0]);
```

하지만 숫자를 `parseInt( ,10)` 을 이용해서 다시 한번 변환하면 sql문이 실행됨...
```js
  const sql = `
    SELECT * FROM books 
    WHERE title LIKE CONCAT("%", ?, "%") 
    LIMIT ? OFFSET ?`;

const { rows, conn } = await getSqlQueryResult(sql, ['모던',parseInt(limit,10),parseInt(offset,10)]);
```

**Comment by hyemin12** [comment]
MySQL은 LIMIT 및 OFFSET 절에서 바인딩 매개변수를 지원하지 않기 때문에 바인딩 매개변수 대신 직접 값을 쿼리에 삽입하는 방식으로 해결함

```js
// booksController.js
const getSearchBooks = async (req, res, next) => {
  const { page, query } = req.query;

  let additional = "";

  if (page) {
    const limit = 6;
    const offset = limit * (page - 1);
    additional = ` LIMIT ${limit} OFFSET ${offset}`;
  }

  const sql = `
    SELECT * FROM books 
    WHERE title LIKE CONCAT("%", ?, "%") 
    ${additional}`;

  try {
    const { rows, conn } = await getSqlQueryResult(sql, [query]);
    res.status(StatusCodes.OK).send({ lists: rows });
    conn.release();
  } catch (err) {
    handleServerError(res, err);
  }
};
```
